"""adiciona isbn ao livro

Revision ID: 398d88f69706
Revises: 7259cbc138af
Create Date: 2026-08-18 08:16:30.056610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398d88f69706'
down_revision: Union[str, Sequence[str], None] = '7259cbc138af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livro', sa.Column('isbn', sa.String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livro', 'isbn')
    # ### end Alembic commands ###
