"""remove telefone do usuario

Revision ID: 7259cbc138af
Revises: f8b4505855b6
Create Date: 2026-08-18 07:52:57.861165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7259cbc138af'
down_revision: Union[str, Sequence[str], None] = 'f8b4505855b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'telefone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('telefone', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
